<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Kbd } from '$lib/components/ui/kbd/index.js';
	import { Label } from '$lib/components/ui/label/index.js';
	import {
		Dialog,
		DialogContent,
		DialogDescription,
		DialogFooter,
		DialogHeader,
		DialogTitle,
		DialogTrigger
	} from '$lib/components/ui/dialog/index.js';
	import {
		Drawer,
		DrawerContent,
		DrawerDescription,
		DrawerFooter,
		DrawerHeader,
		DrawerTitle,
		DrawerTrigger
	} from '$lib/components/ui/drawer/index.js';

	import { onMount, type Snippet } from 'svelte';
	import { useConvexClient } from 'convex-svelte';
	import { api } from '$convex/_generated/api';
	import { accountManager } from '$lib/state/accountManager.svelte';
	import { ChevronDown, Shuffle, Sparkles, Loader, X } from '@lucide/svelte';
	import { MediaQuery } from 'svelte/reactivity';
	import { toast } from 'svelte-sonner';
	import { copyToClipboard } from '$lib/utils/clipboard';
	import { getErrorMessage } from '$lib/utils/error.js';
	import { getTagColor, getTagTextColor } from '$lib/utils/tags.js';

	let { onSubmit, children } = $props<{
		onSubmit?: (payload: { url: string; slug?: string; tags?: string[] }) => void;
		children?: Snippet;
	}>();

	let url = $state('');
	let slug = $state('');
	let tags = $state<string[]>([]);
	let tagInput = $state('');
	let open = $state(false);
	let isGenerating = $state(false);
	let isSubmitting = $state(false);
	let slugTouched = $state(false);
	let aiSuggestions = $state<string[]>([]);
	let isAiGenerating = $state(false);
	let aiError = $state('');
	let errorMessage = $state('');
	let wasOpen = $state(false);

	const isMobile = new MediaQuery('(max-width: 640px)');
	const useDrawer = $derived(isMobile.current);
	let domain = $state('');
	const convex = useConvexClient();
	let hasAutoGenerated = $state(false);

	onMount(() => {
		if (typeof window === 'undefined') return;
		domain = window.location.host;
	});

	const isValidUrl = (urlString: string): boolean => {
		try {
			const parsed = new URL(urlString);
			return parsed.protocol === 'http:' || parsed.protocol === 'https:';
		} catch {
			return false;
		}
	};

	const isUrlValid = $derived(url.trim() && isValidUrl(url.trim()));

	const submit = async () => {
		const trimmedUrl = url.trim();
		if (!trimmedUrl || isSubmitting) return;

		try {
			new URL(trimmedUrl);
		} catch {
			errorMessage = 'Please enter a valid URL';
			return;
		}

		const isValid = isValidUrl(trimmedUrl);
		if (!isValid) {
			errorMessage = 'URL must start with http:// or https://';
			return;
		}
		const auth = accountManager.authArgs;
		if (!auth) {
			errorMessage = 'Please wait while we set up your account.';
			return;
		}

		isSubmitting = true;
		errorMessage = '';
		const trimmedSlug = slug.trim();
		const finalTags = tags.length > 0 ? tags : undefined;

		try {
			const result = await convex.mutation(api.links.create, {
				username: auth.username,
				token: auth.token,
				url: trimmedUrl,
				...(trimmedSlug ? { shortId: trimmedSlug } : {}),
				...(finalTags ? { tags: finalTags } : {})
			});

			onSubmit?.({ url: result.url, slug: result.shortId, tags: result.tags });
			setOpen(false);
			url = '';
			slug = '';
			tags = [];

			if (typeof window !== 'undefined') {
				const shortLink = `${window.location.protocol}//${window.location.host}/${result.shortId}`;
				const copied = await copyToClipboard(shortLink);
				if (copied) {
					toast.success('Short link copied to clipboard');
				} else {
					toast.error('Failed to copy short link');
				}
			}
		} catch (error) {
			errorMessage = getErrorMessage(error, 'Unable to create link. Please try again.');
		} finally {
			isSubmitting = false;
		}
	};

	const setOpen = (nextOpen: boolean) => {
		open = nextOpen;
	};

	const regenerateSlug = async () => {
		const auth = accountManager.authArgs;
		if (!auth || isGenerating) return;
		isGenerating = true;
		try {
			const shortId = (await convex.mutation(api.links.generateShortId, {
				username: auth.username,
				token: auth.token
			})) as string;
			slug = shortId;
			slugTouched = true;
		} catch (error) {
			console.error('Failed to generate short link', error);
		} finally {
			isGenerating = false;
		}
	};

	const suggestWithAi = async () => {
		const auth = accountManager.authArgs;
		const trimmedUrl = url.trim();
		if (!auth || !trimmedUrl || !isValidUrl(trimmedUrl) || isAiGenerating) return;
		isAiGenerating = true;
		aiError = '';
		aiSuggestions = [];
		try {
			const result = (await convex.action(api.ai.suggestSlugs, {
				...auth,
				url: trimmedUrl
			})) as { suggestions: string[]; disabled?: boolean };
			if (result.disabled) {
				aiError = 'AI Suggestions are disabled as of now';
				return;
			}
			aiSuggestions = result.suggestions ?? [];
			if (aiSuggestions.length === 0) {
				aiError = 'Could not generate suggestions';
			}
		} catch {
			aiError = 'AI suggestion failed';
		} finally {
			isAiGenerating = false;
		}
	};

	const maybeAutoGenerateSlug = () => {
		if (!open || slug.trim() || isGenerating || slugTouched || hasAutoGenerated) return;
		hasAutoGenerated = true;
		void regenerateSlug();
	};

	$effect(() => {
		if (!open && wasOpen) {
			slugTouched = false;
			hasAutoGenerated = false;
			aiSuggestions = [];
			isAiGenerating = false;
			aiError = '';
			errorMessage = '';
			tags = [];
			tagInput = '';
		}

		if (open && !wasOpen) {
			maybeAutoGenerateSlug();
		}

		wasOpen = open;
	});

	const handleSubmit = (event: SubmitEvent) => {
		event.preventDefault();
		void submit();
	};
</script>

{#snippet triggerContent()}
	{#if children}
		{@render children?.()}
	{:else}
		<Button size="default" hotkey="c">
			Create link
			<Kbd class="bg-primary-foreground/15 text-primary-foreground">C</Kbd>
		</Button>
	{/if}
{/snippet}

{#snippet formFields()}
	<div class="grid gap-2">
		<Label for="create-link-url">Destination URL</Label>
		<Input
			id="create-link-url"
			placeholder="https://example.com"
			autocomplete="url"
			bind:value={url}
			required
		/>
	</div>
	<div class="relative grid gap-2">
		<Label for="create-link-short-id">Short Link</Label>
		<div class="absolute top-0 right-0 flex gap-1">
			<button
				type="button"
				class="text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-40"
				disabled={!isUrlValid || isAiGenerating}
				title={isAiGenerating ? 'Generating…' : 'Suggest with AI'}
				aria-label="Suggest with AI"
				onclick={() => suggestWithAi()}
			>
				{#if isAiGenerating}
					<Loader class="h-4 w-4 animate-spin" />
				{:else}
					<Sparkles class="h-4 w-4" />
				{/if}
			</button>
			<button
				type="button"
				class="text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-40"
				disabled={!accountManager.activeAccount || isGenerating}
				title={isGenerating ? 'Generating…' : 'Generate new short id'}
				aria-label="Generate new short id"
				onclick={() => regenerateSlug()}
			>
				<Shuffle class={isGenerating ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />
			</button>
		</div>
		<div class="flex">
			<div class="relative">
				<Input
					value={domain}
					disabled
					class="w-40 rounded-r-none pr-8"
					aria-label="Short link domain"
				/>
				<ChevronDown
					class="pointer-events-none absolute top-1/2 right-2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground"
				/>
			</div>
			<Input
				id="create-link-short-id"
				placeholder="(optional)"
				autocomplete="off"
				autocapitalize="none"
				spellcheck={false}
				class="rounded-l-none"
				bind:value={slug}
				oninput={() => {
					slugTouched = true;
					errorMessage = '';
				}}
			/>
		</div>
		{#if aiSuggestions.length > 0}
			<div class="flex flex-wrap gap-1.5">
				{#each aiSuggestions as suggestion (suggestion)}
					<button
						type="button"
						class="inline-flex items-center gap-1 rounded-md border border-border bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground transition-colors hover:border-primary hover:text-foreground"
						onclick={() => {
							slug = suggestion;
							slugTouched = true;
							aiSuggestions = [];
							aiError = '';
						}}
					>
						<Sparkles class="h-3 w-3" />
						{suggestion}
					</button>
				{/each}
			</div>
		{:else if aiError}
			<p class="text-xs text-muted-foreground">{aiError}</p>
		{/if}
	</div>
	<div class="grid gap-2">
		<Label for="create-link-tags">Tags</Label>
		<div class="flex flex-wrap gap-2 rounded-md border border-input bg-background px-3 py-2">
			{#each tags as tag (tag)}
				<span
					class="inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-xs font-medium"
					style="background-color: {getTagColor(tag)}; color: {getTagTextColor(tag)}"
				>
					{tag}
					<button
						type="button"
						class="ml-0.5 inline-flex h-3 w-3 items-center justify-center rounded-full hover:bg-black/10"
						onclick={() => {
							tags = tags.filter((t) => t !== tag);
						}}
					>
						<X class="h-2.5 w-2.5" />
					</button>
				</span>
			{/each}
			<input
				id="create-link-tags"
				class="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
				placeholder={tags.length === 0 ? 'Add tags (press Enter or Space)' : ''}
				bind:value={tagInput}
				onkeydown={(e) => {
					if (e.key === 'Enter' || e.key === ' ') {
						e.preventDefault();
						const trimmed = tagInput.trim().toLowerCase();
						const validTag = trimmed.replace(/[^a-z0-9_\-/]/g, '');
						if (validTag && !tags.includes(validTag)) {
							tags = [...tags, validTag];
						}
						tagInput = '';
					} else if (e.key === 'Backspace' && tagInput === '' && tags.length > 0) {
						tags = tags.slice(0, -1);
					}
				}}
			/>
		</div>
	</div>
	{#if errorMessage}
		<p class="text-sm text-destructive">{errorMessage}</p>
	{/if}
{/snippet}

{#snippet footerButtons()}
	<Button type="button" variant="outline" onclick={() => setOpen(false)} disabled={isSubmitting}>
		Cancel
	</Button>
	<Button type="submit" disabled={isSubmitting || !isUrlValid}>
		{isSubmitting ? 'Creating…' : 'Create link'}
	</Button>
{/snippet}

{#if useDrawer}
	<Drawer bind:open>
		<DrawerTrigger>{@render triggerContent()}</DrawerTrigger>
		<DrawerContent>
			<DrawerHeader class="">
				<DrawerTitle>Create link</DrawerTitle>
				<DrawerDescription>Share a short link with a custom slug.</DrawerDescription>
			</DrawerHeader>
			<form class="mt-4 grid gap-4" onsubmit={handleSubmit}>
				{@render formFields()}
				<DrawerFooter class="">{@render footerButtons()}</DrawerFooter>
			</form>
		</DrawerContent>
	</Drawer>
{:else}
	<Dialog bind:open>
		<DialogTrigger>{@render triggerContent()}</DialogTrigger>
		<DialogContent>
			<DialogHeader class="">
				<DialogTitle>Create link</DialogTitle>
				<DialogDescription>Share a short link with a custom slug.</DialogDescription>
			</DialogHeader>
			<form class="grid gap-4" onsubmit={handleSubmit}>
				{@render formFields()}
				<DialogFooter class="">{@render footerButtons()}</DialogFooter>
			</form>
		</DialogContent>
	</Dialog>
{/if}
